[package]
name = "day_4"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
regex = "1.10.2"
utils = { path = "../utils" }
lazy_static = "1.4.0"

[features]
default = ["part_2"]
part_1 = []
part_2 = ["part_1"]
